### PR TITLE
Update the max date of the date pickers

### PR DESCRIPTION
**Pull request by deon1**
Update the max date of the date pickers

https://github.com/A24Group/A24EmberLib/issues/566

#### Testing
 - click on clients, select one, list sites, select one, linked info, edit billing path
 - click on attendance, select timesheet, view, edit shift entry

### CODE REVIEW

**Comment by nauderuan** [comment]
Local test:
* On the billing path edit the max year is now 2070, I think it should be 2040 right? The date picker on the Vacancy datagrid is correct and shows max as 2040...Seems the datepicker on the timesheet edit shift entry is also correct

**Comment by deon1** [comment]
The billing path date-picker adds 50 years to the current date to get the max date.

**Comment by nauderuan** [comment]
ok

**Comment by nauderuan** [comment]
:+1: local test

**Comment by Flebe** [comment]
:+1: on staging test

**Pull request merged**
